export const CITY_DATABASE = [
  "New York", "London", "Karachi", "Lahore", "Islamabad", "Dubai", "Abu Dhabi",
  "Riyadh", "Jeddah", "Doha", "Muscat", "Manama", "Kuwait City", "Cairo",
  "Alexandria", "Amman", "Beirut", "Baghdad", "Tehran", "Istanbul", "Ankara",
  "Paris", "Berlin", "Madrid", "Rome", "London", "Moscow", "Tokyo", "Seoul",
  "Beijing", "Shanghai", "Hong Kong", "Singapore", "Bangkok", "Jakarta",
  "Kuala Lumpur", "Manila", "Hanoi", "Ho Chi Minh City", "Sydney", "Melbourne",
  "Auckland", "Toronto", "Vancouver", "Montreal", "Los Angeles", "Chicago",
  "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas",
  "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte",
  "San Francisco", "Indianapolis", "Seattle", "Denver", "Washington", "Boston",
  "El Paso", "Nashville", "Detroit", "Oklahoma City", "Portland", "Las Vegas",
  "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", "Tucson",
  "Fresno", "Sacramento", "Mesa", "Kansas City", "Atlanta", "Long Beach",
  "Colorado Springs", "Raleigh", "Miami", "Virginia Beach", "Omaha", "Oakland",
  "Minneapolis", "Tulsa", "Arlington", "New Orleans", "Wichita", "Cleveland",
  "Tampa", "Bakersfield", "Aurora", "Anaheim", "Honolulu", "Santa Ana",
  "Riverside", "Corpus Christi", "Lexington", "Henderson", "Stockton",
  "Saint Paul", "Cincinnati", "St. Louis", "Pittsburgh", "Greensboro",
  "Lincoln", "Anchorage", "Plano", "Orlando", "Irvine", "Newark", "Durham",
  "Chula Vista", "Toledo", "Fort Wayne", "St. Petersburg", "Laredo", "Jersey City",
  "Chandler", "Madison", "Lubbock", "Scottsdale", "Reno", "Buffalo", "Gilbert",
  "Glendale", "North Las Vegas", "Winston-Salem", "Chesapeake", "Norfolk",
  "Fremont", "Garland", "Irving", "Hialeah", "Richmond", "Boise", "Spokane",
  "Baton Rouge", "Des Moines", "Modesto", "Fayetteville", "Tacoma", "Shreveport",
  "Fontana", "Oxnard", "Aurora", "Yonkers", "Akron", "Little Rock", "Augusta",
  "Mobile", "Tallahassee", "Huntsville", "Grand Rapids", "Overland Park",
  "Knoxville", "Worcester", "Brownsville", "Newport News", "Santa Clarita",
  "Providence", "Fort Lauderdale", "Chattanooga", "Tempe", "Oceanside",
  "Garden Grove", "Rancho Cucamonga", "Cape Coral", "Santa Rosa", "Vancouver",
  "Sioux Falls", "Peoria", "Ontario", "Jackson", "Elk Grove", "Springfield",
  "Pembroke Pines", "Salem", "Corona", "Eugene", "McKinney", "Fort Collins",
  "Lancaster", "Cary", "Palmdale", "Hayward", "Salinas", "Frisco", "Springfield",
  "Pasadena", "Macon", "Alexandria", "Pomona", "Lakewood", "Sunnyvale",
  "Escondido", "Hollywood", "Clarksville", "Rockford", "Joliet", "Naperville",
  "Paterson", "Savannah", "Bridgeport", "Mesquite", "Killeen", "Syracuse",
  "McAllen", "Pasadena", "Bellevue", "Fullerton", "Orange", "Dayton", "Miramar",
  "Thornton", "West Valley City", "Olathe", "Hampton", "Warren", "Grand Prairie",
  "Sterling Heights", "Columbia", "Charleston", "Carrollton", "Elizabeth",
  "Hartford", "Surprise", "Denton", "Waco", "Visalia", "Stamford", "New Haven",
  "Victorville", "Kent", "Abilene", "Roseville", "Lafayette", "Simi Valley",
  "Athens", "Midland", "Pearland", "Vallejo", "Allentown", "Berkeley", "Ann Arbor",
  "Columbia", "Evansville", "Fargo", "Wilmington", "Arvada", "Provo", "Odessa",
  "Norman", "Round Rock", "Carlsbad", "Murrieta", "Palm Bay", "Lansing",
  "Marietta", "High Point", "West Jordan", "Waterbury", "Everett", "Richardson",
  "Billings", "Lowell", "Gresham", "San Buenaventura", "Pueblo", "West Covina",
  "El Monte", "Westminster", "Norwalk", "Burbank", "Inglewood", "Rialto",
  "Tyler", "Elgin", "South Bend", "Greeley", "Davie", "Daly City", "Centennial",
  "Boulder", "West Palm Beach", "Pompano Beach", "Costa Mesa", "Downey",
  "Clovis", "Manchester", "Miami Gardens", "Cambridge", "Sugar Land", "Temecula",
  "Broken Arrow", "Meridian", "Vacaville", "Lakeland", "Lewisville", "Enterprise",
  "Sandy Springs", "Murfreesboro", "Tuscaloosa", "Davenport", "Edmond", "Gainesville",
  "Fairfield", "Albany", "Lawrence", "San Angelo", "Kennewick", "San Mateo",
  "New Bedford", "Brockton", "Quincy", "Fall River", "Newton", "Somerville",
  "Framingham", "Waltham", "Malden", "Brookline", "Medford", "Taunton", "Weymouth",
  "Revere", "Peabody", "Methuen", "Barnstable", "Pittsfield", "Attleboro",
  "Arlington", "Everett", "Salem", "Westfield", "Leominster", "Fitchburg",
  "Holyoke", "Beverly", "Marlborough", "Woburn", "Chelsea", "Amherst", "Braintree",
  "Randolph", "Watertown", "Franklin", "Lexington", "Needham", "Tewksbury",
  "Gloucester", "Northampton", "Agawam", "Dracut", "Melrose", "Saugus",
  "Bridgewater", "Danvers", "Marshfield", "Wakefield", "Reading", "Milton",
  "Dedham", "Burlington", "Stoneham", "Winchester", "Belmont", "Marblehead",
  "Swampscott", "Sudbury", "Weston", "Wayland", "Concord", "Lincoln", "Carlisle"
];
