export const SKILLS_DATABASE = [
  "JavaScript", "TypeScript", "React", "Node.js", "Express", "MongoDB", "SQL", "PostgreSQL",
  "Python", "Django", "Flask", "Java", "Spring", "C++", "C#", ".NET", "PHP", "Laravel",
  "HTML", "CSS", "Sass", "Tailwind CSS", "Bootstrap", "Vue.js", "Angular", "Next.js",
  "Docker", "Kubernetes", "AWS", "Azure", "Google Cloud", "Firebase", "Git", "GitHub",
  "Agile", "Scrum", "Project Management", "UI/UX Design", "Figma", "Adobe XD",
  "Photoshop", "Illustrator", "SEO", "Digital Marketing", "Content Writing",
  "Data Analysis", "Machine Learning", "Artificial Intelligence", "Deep Learning",
  "Cybersecurity", "Network Engineering", "System Administration", "Linux", "Unix",
  "Mobile App Development", "Swift", "Kotlin", "React Native", "Flutter",
  "Communication", "Leadership", "Teamwork", "Problem Solving", "Critical Thinking",
  "Time Management", "Adaptability", "Creativity", "Customer Service", "Sales",
  "Marketing Strategy", "Financial Analysis", "Accounting", "HR Management",
  "Public Speaking", "Writing", "Editing", "Proofreading", "Translation",
  "Microsoft Office", "Excel", "PowerPoint", "Word", "Google Workspace",
  "Data Visualization", "Tableau", "Power BI", "R", "MATLAB", "Statistics",
  "Quality Assurance", "Testing", "Unit Testing", "Integration Testing",
  "DevOps", "CI/CD", "Jenkins", "Ansible", "Terraform", "GraphQL", "REST API",
  "WebSockets", "Redux", "MobX", "Zustand", "Recoil", "Webpack", "Vite", "Babel",
  "Jest", "Cypress", "Enzyme", "Storybook", "Responsive Design", "Accessibility",
  "Web Performance", "Security", "OAuth", "JWT", "Microservices", "Serverless",
  "Blockchain", "Solidity", "Smart Contracts", "Web3", "Unity", "Unreal Engine",
  "Game Development", "3D Modeling", "Blender", "Maya", "Video Editing",
  "Premiere Pro", "After Effects", "Final Cut Pro", "Copywriting", "Blogging",
  "Social Media Management", "Email Marketing", "PPC", "Google Ads", "Facebook Ads",
  "E-commerce", "Shopify", "WooCommerce", "Magento", "Salesforce", "CRM",
  "ERP", "SAP", "Oracle", "Business Intelligence", "Market Research",
  "Strategic Planning", "Operations Management", "Supply Chain Management",
  "Logistics", "Inventory Management", "Procurement", "Contract Negotiation",
  "Legal Research", "Compliance", "Risk Management", "Internal Audit",
  "Taxation", "Budgeting", "Forecasting", "Investment Banking", "Portfolio Management",
  "Trading", "Economics", "Psychology", "Sociology", "Education", "Teaching",
  "Curriculum Development", "Training", "Coaching", "Mentoring", "Counseling",
  "Healthcare", "Nursing", "Medicine", "Pharmacy", "Biology", "Chemistry", "Physics",
  "Mathematics", "Engineering", "Mechanical Engineering", "Electrical Engineering",
  "Civil Engineering", "Chemical Engineering", "Aerospace Engineering",
  "Biomedical Engineering", "Environmental Engineering", "Architecture",
  "Interior Design", "Fashion Design", "Graphic Design", "Motion Graphics",
  "Photography", "Videography", "Sound Design", "Music Production", "Event Planning",
  "Hospitality", "Tourism", "Real Estate", "Construction", "Manufacturing",
  "Automotive", "Aviation", "Maritime", "Agriculture", "Sustainability",
  "Renewable Energy", "Social Work", "Non-profit Management", "Fundraising",
  "Public Relations", "Journalism", "Media Production", "Political Science",
  "International Relations", "History", "Philosophy", "Literature", "Linguistics"
];
